# Generated by Django 2.1.1 on 2019-10-11 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AID', models.IntegerField(primary_key=True, serialize=False)),
                ('AName', models.CharField(max_length=30)),
                ('A_Addr', models.TextField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BID', models.IntegerField(primary_key=True, serialize=False)),
                ('BName', models.CharField(max_length=30)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('OID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('BID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
    ]
